import { useLayoutEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Building2, Eye, EyeOff, HardHat, LockKeyhole, Mail, ShieldCheck, UserRound, Wrench } from "lucide-react";
import { signInWithProvider } from "../lib/auth";
const info={
 "Facility Manager":{icon:Building2,accent:"Operational control, workforce intelligence and system governance."},
 "Supervisor":{icon:ShieldCheck,accent:"Verification, conflict resolution and SLA oversight."},
 "Technician":{icon:HardHat,accent:"Assigned work, progress updates and maintenance completion."},
 "Requester":{icon:UserRound,accent:"Service request creation and live status tracking."},
};
const USERS_KEY="maintenax-users";
const seed=[
 {username:"admin",email:"admin@maintenax.app",password:"admin123",role:"Facility Manager"},
 {username:"supervisor",email:"supervisor@maintenax.app",password:"super123",role:"Supervisor"},
 {username:"technician",email:"technician@maintenax.app",password:"tech123",role:"Technician"},
 {username:"requester",email:"requester@maintenax.app",password:"user123",role:"Requester"},
];
function users(){try{const x=JSON.parse(localStorage.getItem(USERS_KEY)||"null");if(Array.isArray(x))return x}catch{} localStorage.setItem(USERS_KEY,JSON.stringify(seed));return seed}
export default function Login({role,onBack,onLogin}){
 const d=info[role]||info.Requester,Icon=d.icon;
 const [mode,setMode]=useState("signin"),[username,setUsername]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useLayoutEffect(()=>{document.documentElement.classList.add("dark")},[]);
 function submit(e){e.preventDefault();setError("");setNotice("");const all=users();const id=(username||email).trim().toLowerCase();
  if(mode==="signup"){if(!username.trim()||!email.trim())return setError("Name and email are required.");if(password.length<8)return setError("Password must contain at least 8 characters.");if(password!==confirm)return setError("Passwords do not match.");if(all.some(x=>x.email.toLowerCase()===email.trim().toLowerCase()||x.username.toLowerCase()===username.trim().toLowerCase()))return setError("An account with this username or email already exists.");const a={username:username.trim(),email:email.trim(),password,role};localStorage.setItem(USERS_KEY,JSON.stringify([...all,a]));setNotice("Account created. Signing you in…");setTimeout(()=>onLogin(a.username,a.password,role),250);return}
  const a=all.find(x=>(x.username.toLowerCase()===id||x.email.toLowerCase()===id)&&x.password===password&&x.role===role);if(!a)return setError(`We couldn't verify this ${role.toLowerCase()} account.`);onLogin(a.username,a.password,role)}
 async function provider(name){setError("");try{await signInWithProvider(name,role)}catch(e){setError(e.message)}}
 return <main className="min-h-screen bg-[#040a10] p-4 text-white lg:p-6"><div className="mx-auto grid min-h-[calc(100vh-3rem)] max-w-[1480px] overflow-hidden rounded-[28px] border border-slate-800 bg-[#07111a] shadow-[0_30px_100px_rgba(0,0,0,.55)] lg:grid-cols-[1.05fr_.95fr]">
 <section className="relative hidden overflow-hidden border-r border-white/10 bg-[#071827] p-14 lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 opacity-25" style={{backgroundImage:"linear-gradient(#ffffff0d 1px,transparent 1px),linear-gradient(90deg,#ffffff0d 1px,transparent 1px)",backgroundSize:"38px 38px"}}/><div className="absolute -right-32 top-28 h-96 w-96 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-300/10 ring-1 ring-cyan-300/20"><Wrench className="h-6 w-6 text-cyan-300"/></span><div><div className="text-3xl font-black tracking-[-.04em]">Maintena<span className="text-cyan-300">X</span></div><p className="text-[10px] font-bold tracking-[.2em] text-slate-500">ADAPTIVE MAINTENANCE INTELLIGENCE</p></div></div><div className="mt-28"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-1.5 text-xs font-bold text-cyan-200"><Icon className="h-4 w-4"/>{role}</span><h1 className="mt-6 text-5xl font-black leading-[1.04] tracking-[-.045em]">One maintenance system.<br/><span className="text-cyan-300">Every decision connected.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300">{d.accent} MaintenaX connects requests, people, resources, exceptions and operational intelligence in one secure workspace.</p></div></div><div className="relative flex items-center justify-between border-t border-white/10 pt-6 text-xs text-slate-500"><span>SECURE ACCESS</span><span>ROLE-BASED CONTROL</span><span>AUDIT READY</span></div></section>
 <section className="flex items-center p-7 sm:p-12 xl:p-16"><div className="mx-auto w-full max-w-[480px]"><button onClick={onBack} className="mb-8 flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Change role</button><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">{role} access</p><h2 className="mt-3 text-4xl font-black tracking-tight">{mode==="signin"?"Sign in to MaintenaX":"Create your account"}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{mode==="signin"?"Continue to your secure workspace.":"Your account will be created for the selected role."}</p>
 <div className="mt-7"><button onClick={()=>provider("google")} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 text-sm font-semibold hover:border-slate-500 hover:bg-slate-800"><span className="text-base font-black">G</span>Continue with Google</button></div>
 <div className="my-6 flex items-center gap-3 text-[10px] font-bold tracking-[.14em] text-slate-600"><span className="h-px flex-1 bg-slate-800"/>OR USE CREDENTIALS<span className="h-px flex-1 bg-slate-800"/></div>
 <form onSubmit={submit} className="space-y-4">{mode==="signup"&&<Field label="Username" icon={UserRound}><input value={username} onChange={e=>setUsername(e.target.value)} required className="auth-input" placeholder="Choose a username"/></Field>}<Field label={mode==="signin"?"Username or email":"Work email"} icon={mode==="signin"?UserRound:Mail}><input type={mode==="signin"?"text":"email"} value={mode==="signin"?username:email} onChange={e=>mode==="signin"?setUsername(e.target.value):setEmail(e.target.value)} required className="auth-input pl-12" placeholder={mode==="signin"?"Enter username or email":"name@company.com"}/></Field><Field label="Password" icon={LockKeyhole}><div className="relative"><input value={password} onChange={e=>setPassword(e.target.value)} required type={show?"text":"password"} className="auth-input pl-12 pr-12" placeholder="Enter password"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-slate-400">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></Field>{mode==="signup"&&<Field label="Confirm password" icon={LockKeyhole}><input value={confirm} onChange={e=>setConfirm(e.target.value)} required type={show?"text":"password"} className="auth-input" placeholder="Confirm password"/></Field>}{error&&<div className="rounded-xl border border-rose-900 bg-rose-950/30 px-4 py-3 text-sm leading-5 text-rose-300">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-900 bg-emerald-950/30 px-4 py-3 text-sm text-emerald-300">{notice}</div>}<button className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-cyan-400 font-bold text-slate-950 shadow-lg shadow-cyan-500/10 hover:bg-cyan-300">{mode==="signin"?"Sign in":"Create account"}<ArrowRight className="h-4 w-4"/></button></form>
 <p className="mt-6 text-center text-sm text-slate-400">{mode==="signin"?"New to MaintenaX?":"Already have an account?"} <button onClick={()=>{setMode(mode==="signin"?"signup":"signin");setError("");setNotice("")}} className="font-bold text-cyan-300 hover:text-cyan-200">{mode==="signin"?"Create account":"Sign in"}</button></p></div></section></div></main>}
function Field({label,icon:Icon,children}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-200">{label}</span><div className="relative"><Icon className="pointer-events-none absolute left-4 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-slate-500"/>{children}</div></label>}
